# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Withauth' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'testing all functions' do
    @driver.get('http://localhost:3000/')
    @driver.find_element(:link_text, 'Войти').click
    sleep 1
    @driver.find_element(:link_text, 'Зарегистрироваться').click
    sleep 1
    @driver.find_element(:id, 'user_email').click
    @driver.find_element(:id, 'user_email').send_keys('ForgedWithLove@yandex.ru')
    @driver.find_element(:id, 'user_password').click
    @driver.find_element(:id, 'user_password').send_keys('Nikita98')
    sleep 1
    @driver.find_element(:css, 'body > div').click
    @driver.find_element(:name, 'commit').click
    sleep 1
    @driver.find_element(:id, 'session_email').click
    @driver.find_element(:id, 'session_email').send_keys('ForgedWithLove@yandex.ru')
    @driver.find_element(:id, 'session_password').click
    @driver.find_element(:id, 'session_password').send_keys('Nikita98')
    sleep 1
    @driver.find_element(:name, 'commit').click
    sleep 1
    @driver.find_element(:link_text, 'Нахождение дружественных чисел').click
    sleep 1
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('10000')
    sleep 1
    @driver.find_element(:name, 'commit').click
    sleep 4
    @driver.find_element(:link_text, 'Повторить вычисления').click
    @driver.find_element(:id, 'v1').click
    @driver.find_element(:id, 'v1').send_keys('5000')
    sleep 1
    @driver.find_element(:name, 'commit').click
    sleep 2
    @driver.find_element(:link_text, 'Повторить вычисления').click
    @driver.find_element(:link_text, 'Главная').click
    @driver.find_element(:link_text, 'Показать всех пользователей').click
    sleep 1
    @driver.find_element(:css, 'tr:nth-child(2) > td:nth-child(2) > a').click
    sleep 1
    @driver.find_element(:css, 'button').click
  end
end
